{{ range $ds := .Values.accounts }}
kind: Service
apiVersion: v1
metadata:
  name: oeml-api-{{ .name | lower }}
  annotations:
    'consul.hashicorp.com/service-tags': coinapi-marketaccesstrading
    'consul.hashicorp.com/service-meta-ShardingKey': {{ .name | upper }}
  labels:
    app: oeml-api-{{ .name | lower }}
spec:
  selector:
    app: oeml-api-{{ .name | lower }}
  ports:
    - name: http
      port: 80
---
{{- end }}
