{{ range $ds := .Values.accounts }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oeml-api-{{ .name | lower }}
  labels:
    app: oeml-api
    version: {{ $.Values.oemlAPI.tag | default $.Chart.AppVersion | quote }}
spec:
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      name: oeml-api-{{ .name | lower }}
  template:
    metadata:
    {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        name: oeml-api-{{ .name | lower }}
        app: oeml-api
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}
          env:
            {{- if $.Values.extraEnv }}
              {{ toYaml $.Values.extraEnv | nindent 12 }}
            {{- end }}
            {{- if .env }}
              {{ toYaml .env | nindent 12 }}
            {{- end }}
            - name: OEML__LocalAddress
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.oemlAPI.repository }}:{{ $.Values.oemlAPI.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.oemlAPI.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}

      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
