{{ range $ds := .Values.accounts }}
kind: Service
apiVersion: v1
metadata:
  name: oeml-api-{{ .name | lower }}
  annotations:
    'consul.hashicorp.com/service-tags': 'coinapi-marketaccesstrading,prometheus-metrics'
    'consul.hashicorp.com/service-meta-ShardingKey': {{ .name | upper }}
    'consul.hashicorp.com/service-meta-ems-api-type': 'EXCHANGE'
  labels:
    name: oeml-api-{{ .name | lower }}
    app: oeml-api
spec:
  selector:
    name: oeml-api-{{ .name | lower }}
    app: oeml-api
  ports:
    - name: http
      port: 80
---
{{- end }}
